### ISSUE TITLE
Jakart function update

### ISSUE THREAD

**Issue by stealthgyro** [thewhitespace/UI16-Developer-Patch#1]
Since I'm unable to format code directly on share I figured this might be a little better. Just a quick and dirty fix to do one more check on the update set/application icons to work on Jakarta.

`    function patchIcon(name, className, items, callback) {
      var id = 'snd_ui16dp_' + name + '_menu',
        icon;
      createContextMenu(id, items);
      icon = $('.' + className + ' span.label-icon');
      if (icon.length) {
        icon.snd_ui16dp_menu({
          menu_id: "#" + id,
          callback: callback
        }).css('cursor', 'pointerhand');
        jslog('snd_ui16_developer_patch icon picker patch applied to ' + name + ' picker.');
      } else {
        icon = $('.' + className + " a.btn-icon"); //Jakarta version..
        if (icon.length) {
          icon.snd_ui16dp_menu({
            menu_id: "#" + id,
            callback: callback
          }).css('cursor', 'pointerhand');
          jslog('snd_ui16_developer_patch icon picker patch applied to ' + name + ' picker.');
        } else {
          jslog('snd_ui16_developer_patch icon picker patch unable to find ' + name + ' picker.');
        }
      }
    }
`

better formatted https://paste.ee/p/qmMgs

**Comment by jneale** [comment]
Apologies for the delay in getting to this @stealthgyro - things have been a bit manic!
I've pushed a new version that supports Jakarta and adds some more features too. I'm waiting for my Share account to be fixed before I publish there, but you can download now from dist/... 2.3
Really appreciate the input!
Cheers
