### ISSUE TITLE
Disable/remove the "Unimpersonate" button now that it's native to New york

### ISSUE THREAD

**Issue by jacebenson** [thewhitespace/UI16-Developer-Patch#10]
I'm not sure when you want to do this, but in NY, ServiceNow added the "End Impersonation" to the menu.  As such, this is not needed once all are up to NY.  Any chance you want to change this to be controlled via a property or have the code check if the end link is there?

**Comment by jneale** [comment]
Hey @jacebenson 
Thanks, this is already an option via system properties. Go to UI16 Developer Patch > Properties and turn it off.

![image](https://user-images.githubusercontent.com/1355440/73346210-63be9100-427d-11ea-80ab-790977a76ad2.png)

Cheers!
