### ISSUE TITLE
Patch isn't working on Kingston Patch 5

### ISSUE THREAD

**Issue by n8dagr87** [thewhitespace/UI16-Developer-Patch#4]
I've tried to apply v2.4.2 of this patch to both of our sub-production instances (on Kingston patch 5) but none of the functionality works. The update set was previewed and applied successfully and without any errors in both cases, but the UI hasn't actually changed the way I expected it to. It still appears to be the OOB UI16 with none of the included modifications. I can't find any information on the dependencies for this update set other than UI16, which I've confirmed is active and in use on both instances. I'm happy to provide more information to help identify the issue if you can tell me what you need from me.

**Comment by jneale** [comment]
Sorry for the delay in responding. Thanks for reporting this issue. Did you manage to get it to work?
I've just tested it on Kingston Patch 6 and it worked fine so unfortunately there is not a lot I can do.
Thanks
