### ISSUE TITLE
Doesn't seem to work when user uses dashboards instead of homepages

### ISSUE THREAD

**Issue by BrianMcGough** [thewhitespace/UI16-Developer-Patch#5]
Hi,

First, let me say, I really love and appreciate this library.  It has been great for us because we use the domain picker and have fairly long names, and as an admin, having the extra functionality is great.

Re: the issue we are seeing

On first login, it seems like something gets dereferenced in the loading of this library if the user is using dashboards (which seem to do two redirects) as opposed to homepages (which seem to only do one redirect).  Haven't been able to trace down a fix at this point, but it seems like it must be something in the snd_ui16_developer_patch UI Script.

After the first load with 2 redirects (when it doesn't work, if you hit enter on the url again) which doesn't do the two redirects then it does seem to work.

Anyway we are working on this, but wanted to let you know we had run into this.

Thanks,

Brian

**Comment by BrianMcGough** [comment]
I found a workaround, by changing the system properties, glide.home.page and glide.login.page to $pa_dashboard.do it doesn't do so many redirects, and the library continues to work.  Tried to trace it down in the source, but wasn't able to figure it out.

**Comment by jneale** [comment]
Hi Brian,
Thanks for the great feedback!
I haven't seen this behaviour myself, can you let me know what version of ServiceNow you are using?
James

**Comment by jneale** [comment]
Quick follow up - just tested in Kingston Patch 6 and there is no redirect loop because it's not being loaded. The dashboards don't load the global UI script so the patch doesn't get applied at all (at least from what I'm seeing).
