### ISSUE TITLE
Resizer doesn't work on Madrid with responsive Dashboards enabled

### ISSUE THREAD

**Issue by BrianMcGough** [thewhitespace/UI16-Developer-Patch#7]
There is something about the responsive dashboards in madrid, that when we turned them on, the resizer code either doesn't load, or doesn't load in time to do the resizing of the domain and update set widgets.

**Comment by jneale** [comment]
This is because the responsive dashboards do not load global UI Scripts. You just need to navigate to standard form or list and it will load. If you have a solution for the dashboards I'd be glad to add it in. Thanks
