### ISSUE TITLE
UI16 Resizing does not work properly with ServiceNow's responsive dashboards

### ISSUE THREAD

**Issue by alexjyong** [thewhitespace/UI16-Developer-Patch#9]
We've had issues with this working with the responsive dashboards on our instances.

We not certain if it's because the page doesn't finish the onload or if the dashboard pages that we are using don't load the standard UI scripts.

When you load up the dashboards on a hard reload, the update set selector doesn't expand out fully, the update set icon next to the selector doesn't give options when you click on it; just takes you to the selected update set page.

**Comment by alexjyong** [comment]
So did some more investigating with this. This is technically not a bug on the patch per se, but from what I can see, it's how SN loads UI scripts when you first load from a responsive dashboard.

For whatever reason, Responsive dashboards do NOT load the standard UI scripts, which is why this is getting missed. However, what you can do however, is insert the code wholesale into the banner properties on your instance, since that is always loaded.

https://docs.servicenow.com/bundle/newyork-platform-user-interface/page/administer/navigation-and-ui/concept/c_ExamplesOfHowToModifyTheBanner.html

`glide.product.description`

Next to what value you have for this, put in <script> tags, then put in the UI16 code in there and it should just work with responsive dashboards.

**Comment by jneale** [comment]
Hi @alexjyong - you are correct, it's purely because the dashboards do not load global scripts. You can absolutely hard-code this into your header if you'd like to work around the issue.

Thanks
James
